Snowman
=======

http://derevenets.com/[Snowman] is a native code to C/C++ decompiler, supporting x86, AMD64, and ARM architectures.
You can use it as a link:src/snowman[standalone GUI application], a link:src/nocode[command-line tool], an link:src/ida-plugin[IDA plug-in], a link:https://github.com/radare/radare2-pm/blob/master/db/r2snow[radare2] plug-in, an link:https://github.com/x64dbg/snowman[x64dbg plug-in], or a link:src/nc[library].
Snowman is link:doc/licenses.asciidoc[free software].

Use
---
Clone the https://github.com/yegord/snowman[repository], follow the link:doc/build.asciidoc[build instructions], run the decompiler.
Alternatively, download the http://derevenets.com/[prebuilt packages], unpack, and run.

Contribute
----------
We are not done yet.
We want better generated code, even more convenient GUI, support for other architectures.
Feel free to link:doc/todo.asciidoc[pick a problem], solve it, and send a link:https://github.com/yegord/snowman/pulls[pull request].
Write to our link:http://lists.derevenets.com/mailman/listinfo/snowman[mailing list] if you have questions.

Classner extension
------------------
With this now extension the decompiler automatically tries to create C++ classes based on the originally decompiled code.
When there is enough information given, it might be able to recreate the original class structure as close as possible
But this extension is still in its early stages, so be kind and also let me know about bugs and suggestions, if you want to. :)

Keep in mind that this extension can take an additionally long time to process and generate everything.
For a personal project with over 1000 classes it takes around 1 hour, as an example.
But this can vary for project to project and the size and code of the classes etc.
